--- 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
        app-version: latest
    spec:
      serviceAccountName: petclinic-service-account
      containers:
      - name: petclinic
        image: %image%
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 750Mi
--- 
kind: Service
apiVersion: v1
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: petclinic